DROP TABLE IF EXISTS "User" CASCADE;

CREATE TABLE "User" (
    UserID SERIAL PRIMARY KEY,
    Email VARCHAR(255) UNIQUE NOT NULL,
    PasswordHash TEXT NOT NULL,
    DisplayName VARCHAR(100),
    Role VARCHAR(10) DEFAULT 'USER' CHECK (Role IN ('USER', 'ADMIN')),
    CreatedAt TIMESTAMP DEFAULT NOW()
);
